# Generated by Django 4.2.5 on 2023-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_alter_category_options_alter_good_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_mark',
            field=models.BooleanField(default=False, null=True, verbose_name='Пометка'),
        ),
        migrations.AlterField(
            model_name='good',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='good',
            name='is_mark',
            field=models.BooleanField(default=False, null=True, verbose_name='Пометка'),
        ),
    ]
