# Generated by Django 4.2.5 on 2023-09-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code_1c',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='Код 1С'),
        ),
        migrations.AddField(
            model_name='good',
            name='code_1c',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='Код 1С'),
        ),
    ]
