# Generated by Django 4.2.5 on 2023-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_category_code_1c_good_code_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='art',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Артикул'),
        ),
    ]
