# Generated by Django 4.2.5 on 2023-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0007_category_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='art',
        ),
        migrations.AddField(
            model_name='good',
            name='art',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Артикул'),
        ),
    ]
