# Generated by Django 4.2.5 on 2023-09-07 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_amount_alter_order_date_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Строка заказ клиента', 'verbose_name_plural': 'Строки заказа клиента'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 7, 42, 45, 997114), verbose_name='Дата'),
        ),
    ]
