# Generated by Django 4.2.5 on 2023-09-07 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_orderitem_options_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 7, 54, 27, 964359), verbose_name='Дата'),
        ),
    ]
