# Generated by Django 4.2.5 on 2023-09-07 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_order_customer_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('shipped', 'Доставлен'), ('confirmed', 'Подтвержден')], default='created', max_length=12, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 8, 56, 19, 403169), verbose_name='Дата'),
        ),
    ]
