# Generated by Django 4.2.5 on 2023-09-08 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 20, 1, 47, 986719), null=True, verbose_name='Дата'),
        ),
    ]
