# Generated by Django 4.2.5 on 2023-09-08 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0003_alter_category_comment_alter_category_is_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True, verbose_name='Количество')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка корзины',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
