# Generated by Django 4.2.5 on 2023-09-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
