# Generated by Django 4.2.5 on 2023-09-08 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0005_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_app.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка избранного',
                'verbose_name_plural': 'Избранное',
            },
        ),
    ]
